/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);                    /* Function assigned for the Cortex-M7F */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSdPins(void);                  /* Function assigned for the Cortex-M7F */

/* GPIO_SD_B2_08 (coord F15), FLEXSPI1_A_D0 */
/* Routed pin properties */
#define BOARD_INITXIPFLEXSPI1PINS_FLEXSPI1_A_D0_PERIPHERAL              FLEXSPI1   /*!< Peripheral name */
#define BOARD_INITXIPFLEXSPI1PINS_FLEXSPI1_A_D0_SIGNAL           FLEXSPI_A_DATA0   /*!< Signal name */

/* GPIO_SD_B2_09 (coord H15), FLEXSPI1_A_D1 */
/* Routed pin properties */
#define BOARD_INITXIPFLEXSPI1PINS_FLEXSPI1_A_D1_PERIPHERAL              FLEXSPI1   /*!< Peripheral name */
#define BOARD_INITXIPFLEXSPI1PINS_FLEXSPI1_A_D1_SIGNAL           FLEXSPI_A_DATA1   /*!< Signal name */

/* GPIO_SD_B2_10 (coord H14), FLEXSPI1_A_D2 */
/* Routed pin properties */
#define BOARD_INITXIPFLEXSPI1PINS_FLEXSPI1_A_D2_PERIPHERAL              FLEXSPI1   /*!< Peripheral name */
#define BOARD_INITXIPFLEXSPI1PINS_FLEXSPI1_A_D2_SIGNAL           FLEXSPI_A_DATA2   /*!< Signal name */

/* GPIO_SD_B2_11 (coord F16), FLEXSPI1_A_D3 */
/* Routed pin properties */
#define BOARD_INITXIPFLEXSPI1PINS_FLEXSPI1_A_D3_PERIPHERAL              FLEXSPI1   /*!< Peripheral name */
#define BOARD_INITXIPFLEXSPI1PINS_FLEXSPI1_A_D3_SIGNAL           FLEXSPI_A_DATA3   /*!< Signal name */

/* GPIO_SD_B2_05 (coord E14), FLEXSPI1_A_DQS */
/* Routed pin properties */
#define BOARD_INITXIPFLEXSPI1PINS_FLEXSPI1_A_DQS_PERIPHERAL             FLEXSPI1   /*!< Peripheral name */
#define BOARD_INITXIPFLEXSPI1PINS_FLEXSPI1_A_DQS_SIGNAL            FLEXSPI_A_DQS   /*!< Signal name */

/* GPIO_SD_B2_07 (coord G14), FLEXSPI1_A_CLK */
/* Routed pin properties */
#define BOARD_INITXIPFLEXSPI1PINS_FLEXSPI1_A_CLK_PERIPHERAL             FLEXSPI1   /*!< Peripheral name */
#define BOARD_INITXIPFLEXSPI1PINS_FLEXSPI1_A_CLK_SIGNAL           FLEXSPI_A_SCLK   /*!< Signal name */

/* GPIO_SD_B2_03 (coord E15), FLEXSPI1_B_D0 */
/* Routed pin properties */
#define BOARD_INITXIPFLEXSPI1PINS_FLEXSPI1_B_D0_PERIPHERAL              FLEXSPI1   /*!< Peripheral name */
#define BOARD_INITXIPFLEXSPI1PINS_FLEXSPI1_B_D0_SIGNAL           FLEXSPI_B_DATA0   /*!< Signal name */

/* GPIO_SD_B2_02 (coord H13), FLEXSPI1_B_D1 */
/* Routed pin properties */
#define BOARD_INITXIPFLEXSPI1PINS_FLEXSPI1_B_D1_PERIPHERAL              FLEXSPI1   /*!< Peripheral name */
#define BOARD_INITXIPFLEXSPI1PINS_FLEXSPI1_B_D1_SIGNAL           FLEXSPI_B_DATA1   /*!< Signal name */

/* GPIO_SD_B2_01 (coord J14), FLEXSPI1_B_D2 */
/* Routed pin properties */
#define BOARD_INITXIPFLEXSPI1PINS_FLEXSPI1_B_D2_PERIPHERAL              FLEXSPI1   /*!< Peripheral name */
#define BOARD_INITXIPFLEXSPI1PINS_FLEXSPI1_B_D2_SIGNAL           FLEXSPI_B_DATA2   /*!< Signal name */

/* GPIO_SD_B2_00 (coord J15), FLEXSPI1_B_D3 */
/* Routed pin properties */
#define BOARD_INITXIPFLEXSPI1PINS_FLEXSPI1_B_D3_PERIPHERAL              FLEXSPI1   /*!< Peripheral name */
#define BOARD_INITXIPFLEXSPI1PINS_FLEXSPI1_B_D3_SIGNAL           FLEXSPI_B_DATA3   /*!< Signal name */

/* GPIO_SD_B2_04 (coord F14), FLEXSPI1_A_SS1_B_B_CLK */
/* Routed pin properties */
#define BOARD_INITXIPFLEXSPI1PINS_FLEXSPI1_A_SS1_B_B_CLK_PERIPHERAL     FLEXSPI1   /*!< Peripheral name */
#define BOARD_INITXIPFLEXSPI1PINS_FLEXSPI1_A_SS1_B_B_CLK_SIGNAL  FLEXSPI_A_SS1_B   /*!< Signal name */

/* GPIO_SD_B2_06 (coord F17), FLEXSPI1_A_SS0_B */
/* Routed pin properties */
#define BOARD_INITXIPFLEXSPI1PINS_FLEXSPI1_A_SS0_B_PERIPHERAL           FLEXSPI1   /*!< Peripheral name */
#define BOARD_INITXIPFLEXSPI1PINS_FLEXSPI1_A_SS0_B_SIGNAL        FLEXSPI_A_SS0_B   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitXipFlexSPI1Pins(void);         /* Function assigned for the Cortex-M7F */

/* GPIO_EMC_B2_10 (coord R2), FLEXSPI2_A_SCK */
/* Routed pin properties */
#define BOARD_INITLOGFLEXSPI2PINS_FLEXSPI2_A_SCK_PERIPHERAL             FLEXSPI2   /*!< Peripheral name */
#define BOARD_INITLOGFLEXSPI2PINS_FLEXSPI2_A_SCK_SIGNAL           FLEXSPI_A_SCLK   /*!< Signal name */

/* GPIO_EMC_B2_11 (coord L4), FLEXSPI2_A_SS_B */
/* Routed pin properties */
#define BOARD_INITLOGFLEXSPI2PINS_FLEXSPI2_A_SS_B_PERIPHERAL            FLEXSPI2   /*!< Peripheral name */
#define BOARD_INITLOGFLEXSPI2PINS_FLEXSPI2_A_SS_B_SIGNAL         FLEXSPI_A_SS0_B   /*!< Signal name */

/* GPIO_EMC_B2_13 (coord K5), FLEXSPI2_A_D0 */
/* Routed pin properties */
#define BOARD_INITLOGFLEXSPI2PINS_FLEXSPI2_A_D0_PERIPHERAL              FLEXSPI2   /*!< Peripheral name */
#define BOARD_INITLOGFLEXSPI2PINS_FLEXSPI2_A_D0_SIGNAL           FLEXSPI_A_DATA0   /*!< Signal name */

/* GPIO_EMC_B2_14 (coord M4), FLEXSPI2_A_D1 */
/* Routed pin properties */
#define BOARD_INITLOGFLEXSPI2PINS_FLEXSPI2_A_D1_PERIPHERAL              FLEXSPI2   /*!< Peripheral name */
#define BOARD_INITLOGFLEXSPI2PINS_FLEXSPI2_A_D1_SIGNAL           FLEXSPI_A_DATA1   /*!< Signal name */

/* GPIO_EMC_B2_15 (coord L2), FLEXSPI2_A_D2 */
/* Routed pin properties */
#define BOARD_INITLOGFLEXSPI2PINS_FLEXSPI2_A_D2_PERIPHERAL              FLEXSPI2   /*!< Peripheral name */
#define BOARD_INITLOGFLEXSPI2PINS_FLEXSPI2_A_D2_SIGNAL           FLEXSPI_A_DATA2   /*!< Signal name */

/* GPIO_EMC_B2_16 (coord P2), FLEXSPI2_A_D3 */
/* Routed pin properties */
#define BOARD_INITLOGFLEXSPI2PINS_FLEXSPI2_A_D3_PERIPHERAL              FLEXSPI2   /*!< Peripheral name */
#define BOARD_INITLOGFLEXSPI2PINS_FLEXSPI2_A_D3_SIGNAL           FLEXSPI_A_DATA3   /*!< Signal name */

/* GPIO_EMC_B2_12 (coord M2), FLEXSPI2_A_DQS */
/* Routed pin properties */
#define BOARD_INITLOGFLEXSPI2PINS_FLEXSPI2_A_DQS_PERIPHERAL             FLEXSPI2   /*!< Peripheral name */
#define BOARD_INITLOGFLEXSPI2PINS_FLEXSPI2_A_DQS_SIGNAL            FLEXSPI_A_DQS   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDebugUartsPins(void);          /* Function assigned for the Cortex-M7F */

/* GPIO_DISP_B2_12 (coord B6), SECURE_CAN1_TX */
/* Routed pin properties */
#define BOARD_INITSECURECAN1PINS_SECURE_CAN1_TX_PERIPHERAL                  CAN1   /*!< Peripheral name */
#define BOARD_INITSECURECAN1PINS_SECURE_CAN1_TX_SIGNAL                        TX   /*!< Signal name */

/* GPIO_DISP_B2_13 (coord A5), SECURE_CAN1_RX */
/* Routed pin properties */
#define BOARD_INITSECURECAN1PINS_SECURE_CAN1_RX_PERIPHERAL                  CAN1   /*!< Peripheral name */
#define BOARD_INITSECURECAN1PINS_SECURE_CAN1_RX_SIGNAL                        RX   /*!< Signal name */

/* GPIO_DISP_B2_14 (coord A7), SECURE_CAN1_STBY */
/* Routed pin properties */
#define BOARD_INITSECURECAN1PINS_SECURE_CAN1_STBY_PERIPHERAL              GPIO11   /*!< Peripheral name */
#define BOARD_INITSECURECAN1PINS_SECURE_CAN1_STBY_SIGNAL                 gpio_io   /*!< Signal name */
#define BOARD_INITSECURECAN1PINS_SECURE_CAN1_STBY_CHANNEL                    15U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITSECURECAN1PINS_SECURE_CAN1_STBY_GPIO                    GPIO11   /*!< GPIO peripheral base pointer */
#define BOARD_INITSECURECAN1PINS_SECURE_CAN1_STBY_GPIO_PIN                   15U   /*!< GPIO pin number */
#define BOARD_INITSECURECAN1PINS_SECURE_CAN1_STBY_GPIO_PIN_MASK      (1U << 15U)   /*!< GPIO pin mask */

void BOARD_InitUserButtonsPins(void);         /* Function assigned for the Cortex-M7F */

/* GPIO_DISP_B2_04 (coord C7), USER_LED1 */
/* Routed pin properties */
#define BOARD_INITUSERLEDSPINS_USER_LED1_BOOT_CFG10_PERIPHERAL             GPIO5   /*!< Peripheral name */
#define BOARD_INITUSERLEDSPINS_USER_LED1_BOOT_CFG10_SIGNAL           gpio_mux_io   /*!< Signal name */
#define BOARD_INITUSERLEDSPINS_USER_LED1_BOOT_CFG10_CHANNEL                   5U   /*!< Signal channel */

/* GPIO_DISP_B2_05 (coord C9), USER_LED2 */
/* Routed pin properties */
#define BOARD_INITUSERLEDSPINS_USER_LED2_BOOT_CFG11_PERIPHERAL             GPIO5   /*!< Peripheral name */
#define BOARD_INITUSERLEDSPINS_USER_LED2_BOOT_CFG11_SIGNAL           gpio_mux_io   /*!< Signal name */
#define BOARD_INITUSERLEDSPINS_USER_LED2_BOOT_CFG11_CHANNEL                   6U   /*!< Signal channel */

/* GPIO_DISP_B2_06 (coord C6), USER_LED3 */
/* Routed pin properties */
#define BOARD_INITUSERLEDSPINS_USER_LED3_PERIPHERAL                        GPIO5   /*!< Peripheral name */
#define BOARD_INITUSERLEDSPINS_USER_LED3_SIGNAL                      gpio_mux_io   /*!< Signal name */
#define BOARD_INITUSERLEDSPINS_USER_LED3_CHANNEL                              7U   /*!< Signal channel */

/* GPIO_DISP_B2_07 (coord D6), USER_LED4 */
/* Routed pin properties */
#define BOARD_INITUSERLEDSPINS_USER_LED4_PERIPHERAL                        GPIO5   /*!< Peripheral name */
#define BOARD_INITUSERLEDSPINS_USER_LED4_SIGNAL                      gpio_mux_io   /*!< Signal name */
#define BOARD_INITUSERLEDSPINS_USER_LED4_CHANNEL                              8U   /*!< Signal channel */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitUserLedsPins(void);            /* Function assigned for the Cortex-M7F */

/* GPIO_LPSR_04 (coord N7), SECURITY_I2C5_SDA */
/* Routed pin properties */
#define BOARD_INITSECUREI2CPINS_SECURITY_I2C5_SDA_PERIPHERAL              LPI2C5   /*!< Peripheral name */
#define BOARD_INITSECUREI2CPINS_SECURITY_I2C5_SDA_SIGNAL                     SDA   /*!< Signal name */

/* GPIO_LPSR_05 (coord N8), SECURITY_I2C5_SCL */
/* Routed pin properties */
#define BOARD_INITSECUREI2CPINS_SECURITY_I2C5_SCL_PERIPHERAL              LPI2C5   /*!< Peripheral name */
#define BOARD_INITSECUREI2CPINS_SECURITY_I2C5_SCL_SIGNAL                     SCL   /*!< Signal name */

/* GPIO_LPSR_03 (coord T7), SECURITY_RST */
/* Routed pin properties */
#define BOARD_INITSECUREI2CPINS_SECURITY_RST_BOOT_MODE1_PERIPHERAL        GPIO12   /*!< Peripheral name */
#define BOARD_INITSECUREI2CPINS_SECURITY_RST_BOOT_MODE1_SIGNAL           gpio_io   /*!< Signal name */
#define BOARD_INITSECUREI2CPINS_SECURITY_RST_BOOT_MODE1_CHANNEL               3U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITSECUREI2CPINS_SECURITY_RST_BOOT_MODE1_GPIO              GPIO12   /*!< GPIO peripheral base pointer */
#define BOARD_INITSECUREI2CPINS_SECURITY_RST_BOOT_MODE1_GPIO_PIN              3U   /*!< GPIO pin number */
#define BOARD_INITSECUREI2CPINS_SECURITY_RST_BOOT_MODE1_GPIO_PIN_MASK (1U << 3U)   /*!< GPIO pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSecureI2cPins(void);           /* Function assigned for the Cortex-M7F */

/* GPIO_DISP_B2_10 (coord D9), I2C3_SCL */
/* Routed pin properties */
#define BOARD_INITI2CPINS_I2C3_SCL_PERIPHERAL                             LPI2C3   /*!< Peripheral name */
#define BOARD_INITI2CPINS_I2C3_SCL_SIGNAL                                    SCL   /*!< Signal name */

/* GPIO_DISP_B2_11 (coord A6), I2C3_SDA */
/* Routed pin properties */
#define BOARD_INITI2CPINS_I2C3_SDA_PERIPHERAL                             LPI2C3   /*!< Peripheral name */
#define BOARD_INITI2CPINS_I2C3_SDA_SIGNAL                                    SDA   /*!< Signal name */


#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
