/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v10.0
processor: MIMXRT1176xxxxx
package_id: MIMXRT1176DVMAA
mcu_data: ksdk2_0
processor_version: 10.0.0
pin_labels:
- {pin_num: E13, pin_signal: GPIO_DISP_B1_00, label: ENET_QOS_RX_EN, identifier: ENET_QOS_RX_EN}
- {pin_num: D13, pin_signal: GPIO_DISP_B1_01, label: ENET_QOS_RX_CLK, identifier: ENET_QOS_RX_CLK}
- {pin_num: D11, pin_signal: GPIO_DISP_B1_02, label: ENET_QOS_RX0, identifier: ENET_QOS_RX0}
- {pin_num: E11, pin_signal: GPIO_DISP_B1_03, label: ENET_QOS_RX1, identifier: ENET_QOS_RX1}
- {pin_num: E10, pin_signal: GPIO_DISP_B1_04, label: ENET_QOS_RX2, identifier: ENET_QOS_RX2}
- {pin_num: C11, pin_signal: GPIO_DISP_B1_05, label: ENET_QOS_RX3, identifier: ENET_QOS_RX3}
- {pin_num: D10, pin_signal: GPIO_DISP_B1_06, label: ENET_QOS_TX3, identifier: ENET_QOS_TX3_BOOT_CFG0}
- {pin_num: E12, pin_signal: GPIO_DISP_B1_07, label: ENET_QOS_TX2, identifier: ENET_QOS_TX2_BOOT_CFG1}
- {pin_num: A15, pin_signal: GPIO_DISP_B1_08, label: ENET_QOS_TX1, identifier: ENET_QOS_TX1_BOOT_CFG2}
- {pin_num: C13, pin_signal: GPIO_DISP_B1_09, label: ENET_QOS_TX0, identifier: ENET_QOS_TX0_BOOT_CFG3}
- {pin_num: B14, pin_signal: GPIO_DISP_B1_10, label: ENET_QOS_TX_EN, identifier: ENET_QOS_TX_EN_BOOT_CFG4}
- {pin_num: A14, pin_signal: GPIO_DISP_B1_11, label: ENET_QOS_TX_CLK, identifier: ENET_QOS_TX_CLK_BOOT_CFG5}
- {pin_num: B2, pin_signal: GPIO_EMC_B1_23, label: PWM1_A0, identifier: PWM1_A0}
- {pin_num: J4, pin_signal: GPIO_EMC_B1_25, label: PWM1_A1, identifier: PWM1_A1}
- {pin_num: G5, pin_signal: GPIO_EMC_B1_27, label: PWM1_A2, identifier: PWM1_A2}
- {pin_num: J5, pin_signal: GPIO_EMC_B1_24, label: PWM1_B0, identifier: PWM1_B0}
- {pin_num: J3, pin_signal: GPIO_EMC_B1_26, label: PWM1_B1, identifier: PWM1_B1}
- {pin_num: E5, pin_signal: GPIO_EMC_B1_28, label: PWM1_B2, identifier: PWM1_B2}
- {pin_num: H4, pin_signal: GPIO_EMC_B1_06, label: PWM2_A0, identifier: PWM2_A0}
- {pin_num: F5, pin_signal: GPIO_EMC_B1_08, label: PWM2_A1, identifier: PWM2_A1}
- {pin_num: A2, pin_signal: GPIO_EMC_B1_10, label: PWM2_A2, identifier: PWM2_A2}
- {pin_num: H3, pin_signal: GPIO_EMC_B1_07, label: PWM2_B0, identifier: PWM2_B0}
- {pin_num: A3, pin_signal: GPIO_EMC_B1_09, label: PWM2_B1, identifier: PWM2_B1}
- {pin_num: C2, pin_signal: GPIO_EMC_B1_11, label: PWM2_B2, identifier: PWM2_B2}
- {pin_num: D2, pin_signal: GPIO_EMC_B1_31, label: PWM3_A1, identifier: PWM3_A1}
- {pin_num: E3, pin_signal: GPIO_EMC_B1_30, label: PWM3_B0, identifier: PWM3_B0}
- {pin_num: D1, pin_signal: GPIO_EMC_B1_32, label: PWM3_B1, identifier: PWM3_B1}
- {pin_num: E1, pin_signal: GPIO_EMC_B1_34, label: PWM3_B2, identifier: PWM3_B2}
- {pin_num: F3, pin_signal: GPIO_EMC_B1_00, label: PWM4_A0, identifier: PWM4_A0}
- {pin_num: G4, pin_signal: GPIO_EMC_B1_02, label: PWM4_A1, identifier: PWM4_A1}
- {pin_num: H5, pin_signal: GPIO_EMC_B1_04, label: PWM4_A2, identifier: PWM4_A2}
- {pin_num: F2, pin_signal: GPIO_EMC_B1_01, label: PWM4_B0, identifier: PWM4_B0}
- {pin_num: E4, pin_signal: GPIO_EMC_B1_03, label: PWM4_B1, identifier: PWM4_B1}
- {pin_num: F4, pin_signal: GPIO_EMC_B1_05, label: PWM4_B2, identifier: PWM4_B2}
- {pin_num: B16, pin_signal: GPIO_SD_B1_00, label: SD1_CMD, identifier: SD1_CMD}
- {pin_num: N13, pin_signal: GPIO_AD_06, label: IA1_ADC1_A0, identifier: IA1_ADC1_A0}
- {pin_num: R15, pin_signal: GPIO_AD_08, label: IA2_ADC1_A1, identifier: IA2_ADC1_A1}
- {pin_num: R17, pin_signal: GPIO_AD_10, label: IA3_ADC1_A2, identifier: IA3_ADC1_A2}
- {pin_num: P17, pin_signal: GPIO_AD_12, label: IC1_ADC1_A3, identifier: IC1_ADC12_A3}
- {pin_num: N14, pin_signal: GPIO_AD_14, label: IC2_ADC1_A4, identifier: IC2_ADC12_A4}
- {pin_num: N17, pin_signal: GPIO_AD_16, label: IC3_ADC1_A5, identifier: IC3_ADC12_A5}
- {pin_num: M16, pin_signal: GPIO_AD_18, label: IB1_ADC2_A0, identifier: IB1_ADC2_A0}
- {pin_num: K13, pin_signal: GPIO_AD_20, label: IB2_ADC2_A1, identifier: IB2_ADC2_A1}
- {pin_num: K12, pin_signal: GPIO_AD_22, label: IB3_ADC2_A2, identifier: IB3_ADC2_A2}
- {pin_num: L13, pin_signal: GPIO_AD_24, label: VDC3_ADC2_A6, identifier: VDC3_ADC2_A6_LPUART1_TX}
- {pin_num: T17, pin_signal: GPIO_AD_07, label: IA4_ADC1_B0, identifier: IA4_ADC1_B0}
- {pin_num: R16, pin_signal: GPIO_AD_09, label: IDC1_ADC1_B1, identifier: IDC1_ADC1_B1}
- {pin_num: P16, pin_signal: GPIO_AD_11, label: IDC2_ADC1_B2, identifier: IDC2_ADC1_B2}
- {pin_num: L12, pin_signal: GPIO_AD_13, label: IC4_ADC1_B3, identifier: IC4_ADC12_B3}
- {pin_num: M14, pin_signal: GPIO_AD_15, label: VDC1_ADC1_B4, identifier: VDC1_ADC12_B4}
- {pin_num: N15, pin_signal: GPIO_AD_17, label: VDC2_ADC1_B5, identifier: VDC2_ADC12_B5}
- {pin_num: L16, pin_signal: GPIO_AD_19, label: IB4_ADC2_B0, identifier: IB4_ADC2_B0}
- {pin_num: K14, pin_signal: GPIO_AD_21, label: IDC3_ADC2_B1, identifier: IDC3_ADC2_B1}
- {pin_num: J12, pin_signal: GPIO_AD_23, label: IDC4_ADC2_B2, identifier: IDC4_ADC2_B2}
- {pin_num: M15, pin_signal: GPIO_AD_25, label: VDC4_ADC2_B6, identifier: VDC4_ADC2_B6_LPUART1_RX}
- {pin_num: K4, pin_signal: GPIO_EMC_B2_01, label: ENC1_A, identifier: ENC1_A}
- {pin_num: K3, pin_signal: GPIO_EMC_B2_02, label: ENC1_B, identifier: ENC1_B}
- {pin_num: R1, pin_signal: GPIO_EMC_B2_03, label: ENC2_I, identifier: ENC2_I_ABS_ENC_SYNC}
- {pin_num: R2, pin_signal: GPIO_EMC_B2_10, label: FLEXSPI2_A_SCK, identifier: FLEXSPI2_A_SCK}
- {pin_num: L4, pin_signal: GPIO_EMC_B2_11, label: FLEXSPI2_A_SS_B, identifier: FLEXSPI2_A_SS_B}
- {pin_num: M2, pin_signal: GPIO_EMC_B2_12, label: FLEXSPI2_A_DQS, identifier: FLEXSPI2_A_DQS}
- {pin_num: K5, pin_signal: GPIO_EMC_B2_13, label: FLEXSPI2_A_D0, identifier: FLEXSPI2_A_D0}
- {pin_num: T6, pin_signal: GPIO_LPSR_14, label: SWD_CLK, identifier: SWD_CLK_JTAG_CLK}
- {pin_num: U7, pin_signal: GPIO_LPSR_15, label: SWD_IO, identifier: SWD_DIO_JTAG_TMS}
- {pin_num: G17, pin_signal: GPIO_AD_35, label: SD_PWREN_B, identifier: SD_PWREN_B}
- {pin_num: A16, pin_signal: GPIO_SD_B1_05, label: SD1_D3, identifier: SD1_D3}
- {pin_num: B15, pin_signal: GPIO_SD_B1_04, label: SD1_D2, identifier: SD1_D2}
- {pin_num: B17, pin_signal: GPIO_SD_B1_03, label: SD1_D1, identifier: SD1_D1}
- {pin_num: C15, pin_signal: GPIO_SD_B1_02, label: SD1_D0, identifier: SD1_D0}
- {pin_num: D15, pin_signal: GPIO_SD_B1_01, label: SD1_CLK, identifier: SD1_CLK}
- {pin_num: K16, pin_signal: GPIO_AD_32, label: SD1_CD_B, identifier: SD1_CD_B}
- {pin_num: J16, pin_signal: GPIO_AD_34, label: SD1_VSELECT, identifier: SD1_VSELECT}
- {pin_num: F15, pin_signal: GPIO_SD_B2_08, label: FLEXSPI1_A_D0, identifier: FLEXSPI1_A_D0}
- {pin_num: H15, pin_signal: GPIO_SD_B2_09, label: FLEXSPI1_A_D1, identifier: FLEXSPI1_A_D1}
- {pin_num: H14, pin_signal: GPIO_SD_B2_10, label: FLEXSPI1_A_D2, identifier: FLEXSPI1_A_D2}
- {pin_num: F16, pin_signal: GPIO_SD_B2_11, label: FLEXSPI1_A_D3, identifier: FLEXSPI1_A_D3}
- {pin_num: E15, pin_signal: GPIO_SD_B2_03, label: FLEXSPI1_B_D0, identifier: FLEXSPI1_B_D0}
- {pin_num: H13, pin_signal: GPIO_SD_B2_02, label: FLEXSPI1_B_D1, identifier: FLEXSPI1_B_D1}
- {pin_num: J14, pin_signal: GPIO_SD_B2_01, label: FLEXSPI1_B_D2, identifier: FLEXSPI1_B_D2}
- {pin_num: J15, pin_signal: GPIO_SD_B2_00, label: FLEXSPI1_B_D3, identifier: FLEXSPI1_B_D3}
- {pin_num: E14, pin_signal: GPIO_SD_B2_05, label: FLEXSPI1_A_DQS, identifier: FLEXSPI1_A_DQS}
- {pin_num: G14, pin_signal: GPIO_SD_B2_07, label: FLEXSPI1_A_CLK, identifier: FLEXSPI1_A_CLK}
- {pin_num: F14, pin_signal: GPIO_SD_B2_04, label: FLEXSPI1_A_SS1_B_B_CLK, identifier: FLEXSPI1_A_SS1_B_B_CLK}
- {pin_num: F17, pin_signal: GPIO_SD_B2_06, label: FLEXSPI1_A_SS0_B, identifier: FLEXSPI1_A_SS0_B}
- {pin_num: M4, pin_signal: GPIO_EMC_B2_14, label: FLEXSPI2_A_D1, identifier: FLEXSPI2_A_D1}
- {pin_num: L2, pin_signal: GPIO_EMC_B2_15, label: FLEXSPI2_A_D2, identifier: FLEXSPI2_A_D2}
- {pin_num: K1, pin_signal: GPIO_EMC_B1_40, label: LPUART6_TX, identifier: LPUART6_TX_CCM_CLKO1}
- {pin_num: L1, pin_signal: GPIO_EMC_B1_41, label: LPUART6_RX, identifier: LPUART6_RX_CCM_CLKO2}
- {pin_num: E6, pin_signal: GPIO_EMC_B1_29, label: PWM3_A0, identifier: PWM3_A0}
- {pin_num: E2, pin_signal: GPIO_EMC_B1_33, label: PWM3_A2, identifier: PWM3_A2}
- {pin_num: N3, pin_signal: GPIO_EMC_B2_18, label: ENET_QOS_PHY_INTB, identifier: ENET_QOS_PHY_INTB}
- {pin_num: U2, pin_signal: GPIO_EMC_B2_19, label: ENET_QOS_MDC_3V3, identifier: ENET_QOS_MDC_3V3}
- {pin_num: R3, pin_signal: GPIO_EMC_B2_20, label: ENET_QOS_MDIO_3V3, identifier: ENET_QOS_MDIO_3V3}
- {pin_num: P2, pin_signal: GPIO_EMC_B2_16, label: FLEXSPI2_A_D3, identifier: FLEXSPI2_A_D3}
- {pin_num: M1, pin_signal: GPIO_EMC_B2_04, label: ENC2_A, identifier: ENC2_A}
- {pin_num: N1, pin_signal: GPIO_EMC_B2_05, label: ENC2_B, identifier: ENC2_B}
- {pin_num: C5, pin_signal: GPIO_EMC_B1_12, label: ENC3_I, identifier: ENC3_I_ABS_ENC_SYNC}
- {pin_num: D5, pin_signal: GPIO_EMC_B1_13, label: ENC3_A, identifier: ENC3_A}
- {pin_num: B1, pin_signal: GPIO_EMC_B1_14, label: ENC3_B, identifier: ENC3_B}
- {pin_num: F1, pin_signal: GPIO_EMC_B1_35, label: ENC4_I, identifier: ENC4_I_ABS_ENC_SYNC}
- {pin_num: G1, pin_signal: GPIO_EMC_B1_36, label: ENC4_A, identifier: ENC4_A}
- {pin_num: H1, pin_signal: GPIO_EMC_B1_37, label: ENC4_B, identifier: ENC4_B}
- {pin_num: N6, pin_signal: GPIO_LPSR_00, label: CAN3_TX, identifier: CAN3_TX}
- {pin_num: R6, pin_signal: GPIO_LPSR_01, label: CAN3_RX, identifier: CAN3_RX}
- {pin_num: B6, pin_signal: GPIO_DISP_B2_12, label: SECURE_CAN1_TX, identifier: SECURE_CAN1_TX}
- {pin_num: A5, pin_signal: GPIO_DISP_B2_13, label: SECURE_CAN1_RX, identifier: SECURE_CAN1_RX}
- {pin_num: P6, pin_signal: GPIO_LPSR_02, label: CAN3_STBY, identifier: CAN3_STBY_BOOT_MODE0}
- {pin_num: A7, pin_signal: GPIO_DISP_B2_14, label: SECURE_CAN1_STBY, identifier: SECURE_CAN1_STBY}
- {pin_num: N12, pin_signal: GPIO_AD_00, label: RS485_RXD, identifier: RS485_RXD}
- {pin_num: R14, pin_signal: GPIO_AD_01, label: RS485_TXD, identifier: RS485_TXD}
- {pin_num: P15, pin_signal: GPIO_AD_03, label: RS485_DE, identifier: RS485_DE}
- {pin_num: R13, pin_signal: GPIO_AD_02, label: RS485_RE, identifier: RS485_RE}
- {pin_num: N7, pin_signal: GPIO_LPSR_04, label: SECURITY_I2C5_SDA, identifier: SECURITY_I2C5_SDA}
- {pin_num: N8, pin_signal: GPIO_LPSR_05, label: SECURITY_I2C5_SCL, identifier: SECURITY_I2C5_SCL}
- {pin_num: T7, pin_signal: GPIO_LPSR_03, label: SECURITY_RST, identifier: SECURITY_RST_BOOT_MODE1}
- {pin_num: P8, pin_signal: GPIO_LPSR_06, label: USER_BUTTON1, identifier: USER_BUTTON1}
- {pin_num: R8, pin_signal: GPIO_LPSR_07, label: USER_BUTTON2, identifier: USER_BUTTON2}
- {pin_num: U8, pin_signal: GPIO_LPSR_08, label: USER_BUTTON3, identifier: USER_BUTTON3}
- {pin_num: P5, pin_signal: GPIO_LPSR_09, label: USER_BUTTON4, identifier: USER_BUTTON4}
- {pin_num: C1, pin_signal: GPIO_EMC_B1_15, label: SPI1_SCK_FXIO1_D15, identifier: SPI1_SCK_FXIO1_D15}
- {pin_num: D3, pin_signal: GPIO_EMC_B1_16, label: SPI1_CS_FXIO1_D16, identifier: SPI1_CS_FXIO1_D16}
- {pin_num: B3, pin_signal: GPIO_EMC_B1_17, label: SPI1_MISO_FXIO1_D17, identifier: SPI1_MISO_FXIO1_D17}
- {pin_num: B4, pin_signal: GPIO_EMC_B1_18, label: SPI1_MOSI_FXIO1_D18, identifier: SPI1_MOSI_FXIO1_D18}
- {pin_num: C4, pin_signal: GPIO_EMC_B1_19, label: SPI2_SCK_FXIO1_D19, identifier: SPI2_SCK_FXIO1_D19}
- {pin_num: C3, pin_signal: GPIO_EMC_B1_20, label: SPI2_CS_FXIO1_D20, identifier: SPI2_CS_FXIO1_D20}
- {pin_num: G2, pin_signal: GPIO_EMC_B1_21, label: SPI2_MISO_FXIO1_D21, identifier: SPI2_MISO_FXIO1_D21}
- {pin_num: H2, pin_signal: GPIO_EMC_B1_22, label: SPI2_MOSI_FXIO1_D22, identifier: SPI2_MOSI_FXIO1_D22}
- {pin_num: R5, pin_signal: GPIO_LPSR_10, label: SPI_CS_SEL0, identifier: SPI_CS_SEL0_I2C6_SDA}
- {pin_num: T5, pin_signal: GPIO_LPSR_11, label: SPI_CS_SEL1, identifier: SPI_CS_SEL1_I2C6_SCL_SWO}
- {pin_num: U5, pin_signal: GPIO_LPSR_12, label: ENET_QOS_PHY_RST_B, identifier: ENET_QOS_PHY_RST_B}
- {pin_num: U6, pin_signal: GPIO_LPSR_13, label: JTAG_MOD, identifier: JTAG_MOD}
- {pin_num: D9, pin_signal: GPIO_DISP_B2_10, label: I2C3_SCL, identifier: I2C3_SCL}
- {pin_num: A6, pin_signal: GPIO_DISP_B2_11, label: I2C3_SDA, identifier: I2C3_SDA}
- {pin_num: M13, pin_signal: GPIO_AD_04, label: SPI3_SCK_FXIO2_D04, identifier: SPI3_SCK_FXIO2_D04}
- {pin_num: P13, pin_signal: GPIO_AD_05, label: SPI3_CS_FXIO2_D05, identifier: SPI3_CS_FXIO2_D05}
- {pin_num: L14, pin_signal: GPIO_AD_26, label: SPI3_MISO_FXIO2_D26, identifier: SPI3_MISO_FXIO2_D26}
- {pin_num: N16, pin_signal: GPIO_AD_27, label: SPI3_MOSI_FXIO2_D27, identifier: SPI3_MOSI_FXIO2_D27}
- {pin_num: L17, pin_signal: GPIO_AD_28, label: SPI4_SCK_FXIO2_D28, identifier: SPI4_SCK_FXIO2_D28}
- {pin_num: M17, pin_signal: GPIO_AD_29, label: SPI4_CS_FXIO2_D29, identifier: SPI4_CS_FXIO2_D29}
- {pin_num: K17, pin_signal: GPIO_AD_30, label: SPI4_MISO_FXIO2_D30, identifier: SPI4_MISO_FXIO2_D30}
- {pin_num: J17, pin_signal: GPIO_AD_31, label: SPI4_MOSI_FXIO2_D31, identifier: SPI4_MOSI_FXIO2_D31}
- {pin_num: E8, pin_signal: GPIO_DISP_B2_00, label: DIG_OUT_0, identifier: DIG_OUT_0_BOOT_CFG6}
- {pin_num: F8, pin_signal: GPIO_DISP_B2_01, label: DIG_OUT_1, identifier: DIG_OUT_1_BOOT_CFG7}
- {pin_num: E9, pin_signal: GPIO_DISP_B2_02, label: DIG_OUT_2, identifier: DIG_OUT_2_BOOT_CFG8}
- {pin_num: D7, pin_signal: GPIO_DISP_B2_03, label: DIG_OUT_3, identifier: DIG_OUT_3_BOOT_CFG9}
- {pin_num: C7, pin_signal: GPIO_DISP_B2_04, label: USER_LED1, identifier: USER_LED1_BOOT_CFG10}
- {pin_num: C9, pin_signal: GPIO_DISP_B2_05, label: USER_LED2, identifier: USER_LED2_BOOT_CFG11}
- {pin_num: C6, pin_signal: GPIO_DISP_B2_06, label: USER_LED3, identifier: USER_LED3}
- {pin_num: D6, pin_signal: GPIO_DISP_B2_07, label: USER_LED4, identifier: USER_LED4}
- {pin_num: A4, pin_signal: GPIO_DISP_B2_15, label: WDOG_B, identifier: WDOG_B}
- {pin_num: T1, pin_signal: GPIO_EMC_B2_06, label: PWM1_FAULT, identifier: PWM1_FAULT}
- {pin_num: M3, pin_signal: GPIO_EMC_B2_07, label: PWM2_FAULT, identifier: PWM2_FAULT}
- {pin_num: P1, pin_signal: GPIO_EMC_B2_08, label: PWM3_FAULT, identifier: PWM3_FAULT}
- {pin_num: N2, pin_signal: GPIO_EMC_B2_09, label: PWM4_FAULT, identifier: PWM4_FAULT}
- {pin_num: J1, pin_signal: GPIO_EMC_B1_38, label: DIG_INPUT_0, identifier: DIG_INPUT_0}
- {pin_num: J2, pin_signal: GPIO_EMC_B1_39, label: DIG_INPUT_1, identifier: DIG_INPUT_1}
- {pin_num: T2, pin_signal: GPIO_EMC_B2_17, label: DIG_INPUT_2, identifier: DIG_INPUT_2}
- {pin_num: H17, pin_signal: GPIO_AD_33, label: DIG_INPUT_3, identifier: DIG_INPUT_3}
- {pin_num: K2, pin_signal: GPIO_EMC_B2_00, label: ENC1_I, identifier: ENC1_I_ABS_ENC_SYNC}
- {pin_num: B5, pin_signal: GPIO_DISP_B2_08, label: LPUART8_TX, identifier: LPUART8_TX}
- {pin_num: D8, pin_signal: GPIO_DISP_B2_09, label: LPUART8_RX, identifier: LPUART8_RX}
- {pin_num: N9, pin_signal: GPIO_SNVS_08, label: SPI_CS_SEL0, identifier: SPI_CS_SEL0_SNVS}
- {pin_num: R11, pin_signal: GPIO_SNVS_09, label: SPI_CS_SEL1, identifier: SPI_CS_SEL1_SNVS}
- {pin_num: N10, pin_signal: GPIO_SNVS_04, label: DIG_INPUT_4, identifier: DIG_INPUT_4_SNVS}
- {pin_num: P9, pin_signal: GPIO_SNVS_05, label: DIG_INPUT_5, identifier: DIG_INPUT_5_SNVS}
- {pin_num: M9, pin_signal: GPIO_SNVS_06, label: DIG_INPUT_6, identifier: DIG_INPUT_6_SNVS}
- {pin_num: R9, pin_signal: GPIO_SNVS_07, label: DIG_INPUT_7, identifier: DIG_INPUT_7_SNVS}
- {pin_num: R10, pin_signal: GPIO_SNVS_00, label: DIG_OUT_4, identifier: DIG_OUT_4_SNVS}
- {pin_num: P10, pin_signal: GPIO_SNVS_01, label: DIG_OUT_5, identifier: DIG_OUT_5_SNVS}
- {pin_num: L9, pin_signal: GPIO_SNVS_02, label: DIG_OUT_6, identifier: DIG_OUT_6_SNVS}
- {pin_num: M10, pin_signal: GPIO_SNVS_03, label: DIG_OUT_7, identifier: DIG_OUT_7_SNVS}
power_domains: {ADC_VREFH: '1.8', DCDC_ANA: '1.8', DCDC_ANA_SENSE: '1.8', DCDC_DIG: '1.0', DCDC_DIG_SENSE: '1.0', DCDC_IN: '3.3', DCDC_IN_Q: '3.3', DCDC_LN: '1.8',
  DCDC_LP: '1.8', DCDC_PSWITCH: '3.3', NVCC_DISP1: '1.8', NVCC_DISP2: '3.3', NVCC_EMC1: '3.3', NVCC_EMC2: '3.3', NVCC_GPIO: '3.3', NVCC_LPSR: '3.3', NVCC_SD1: '1.8',
  NVCC_SD2: '3.3', NVCC_SNVS: '1.8', VDDA_1P0: '1.0', VDDA_1P8_IN: '1.8', VDDA_ADC_1P8: '1.8', VDDA_ADC_3P3: '3.3', VDD_LPSR_ANA: '1.8', VDD_LPSR_DIG: '1.0', VDD_LPSR_IN: '3.3',
  VDD_MIPI_1P0: '1.0', VDD_MIPI_1P8: '1.8', VDD_SNVS_ANA: '1.8', VDD_SNVS_DIG: '0.85', VDD_SNVS_IN: '3.3', VDD_SOC_IN: '1.0', VDD_USB_1P8: '1.8', VDD_USB_3P3: '3.3'}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_xbara.h"
#include "fsl_iomuxc.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
        BOARD_InitSdPins();
        BOARD_InitXipFlexSPI1Pins();
        BOARD_InitDebugUartsPins();
        BOARD_InitUserButtonsPins();
        BOARD_InitUserLedsPins();
        BOARD_InitSecureI2cPins();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm7, enableClock: 'true'}
- pin_list: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */




/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitSdPins:
- options: {callFromInitBoot: 'true', coreID: cm7, enableClock: 'true'}
- pin_list:
  - {pin_num: A16, peripheral: USDHC1, signal: 'usdhc_data, 3', pin_signal: GPIO_SD_B1_05}
  - {pin_num: B15, peripheral: USDHC1, signal: 'usdhc_data, 2', pin_signal: GPIO_SD_B1_04}
  - {pin_num: B17, peripheral: USDHC1, signal: 'usdhc_data, 1', pin_signal: GPIO_SD_B1_03}
  - {pin_num: C15, peripheral: USDHC1, signal: 'usdhc_data, 0', pin_signal: GPIO_SD_B1_02}
  - {pin_num: D15, peripheral: USDHC1, signal: usdhc_clk, pin_signal: GPIO_SD_B1_01}
  - {pin_num: B16, peripheral: USDHC1, signal: usdhc_cmd, pin_signal: GPIO_SD_B1_00}
  - {pin_num: K16, peripheral: USDHC1, signal: usdhc_cd_b, pin_signal: GPIO_AD_32}
  - {pin_num: J16, peripheral: USDHC1, signal: usdhc_vselect, pin_signal: GPIO_AD_34}
  - {pin_num: G17, peripheral: USDHC1, signal: usdhc_reset_b, pin_signal: GPIO_AD_35}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitSdPins, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitSdPins(void) {
	CLOCK_EnableClock(kCLOCK_Iomuxc);           /* LPCG on: LPCG is ON. */

	  IOMUXC_SetPinMux(
	      IOMUXC_GPIO_AD_32_USDHC1_CD_B,          /* GPIO_AD_32 is configured as USDHC1_CD_B */
	      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
	  IOMUXC_SetPinMux(
	        IOMUXC_GPIO_AD_32_GPIO_MUX3_IO31,       /* GPIO_AD_32 is configured as GPIO_MUX3_IO31 */
	        0U);
	  IOMUXC_SetPinMux(
	      IOMUXC_GPIO_AD_34_GPIO10_IO01,
	      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
	  IOMUXC_SetPinMux(
	      IOMUXC_GPIO_AD_35_GPIO10_IO02,
	      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
	  IOMUXC_SetPinMux(
	      IOMUXC_GPIO_SD_B1_00_USDHC1_CMD,        /* GPIO_SD_B1_00 is configured as USDHC1_CMD */
	      1U);                                    /* Software Input On Field: Input Path is determined by functionality */
	  IOMUXC_SetPinMux(
	      IOMUXC_GPIO_SD_B1_01_USDHC1_CLK,        /* GPIO_SD_B1_01 is configured as USDHC1_CLK */
	      1U);                                    /* Software Input On Field: Input Path is determined by functionality */
	  IOMUXC_SetPinMux(
	      IOMUXC_GPIO_SD_B1_02_USDHC1_DATA0,      /* GPIO_SD_B1_02 is configured as USDHC1_DATA0 */
	      1U);                                    /* Software Input On Field: Input Path is determined by functionality */
	  IOMUXC_SetPinMux(
	      IOMUXC_GPIO_SD_B1_03_USDHC1_DATA1,      /* GPIO_SD_B1_03 is configured as USDHC1_DATA1 */
	      1U);                                    /* Software Input On Field: Input Path is determined by functionality */
	  IOMUXC_SetPinMux(
	      IOMUXC_GPIO_SD_B1_04_USDHC1_DATA2,      /* GPIO_SD_B1_04 is configured as USDHC1_DATA2 */
	      1U);                                    /* Software Input On Field: Input Path is determined by functionality */
	  IOMUXC_SetPinMux(
	      IOMUXC_GPIO_SD_B1_05_USDHC1_DATA3,      /* GPIO_SD_B1_05 is configured as USDHC1_DATA3 */
	      1U);                                    /* Software Input On Field: Input Path is determined by functionality */
	  IOMUXC_GPR->GPR43 = ((IOMUXC_GPR->GPR43 &
	    (~(IOMUXC_GPR_GPR43_GPIO_MUX3_GPIO_SEL_HIGH_MASK))) /* Mask bits to zero which are setting */
	      | IOMUXC_GPR_GPR43_GPIO_MUX3_GPIO_SEL_HIGH(0x8000U) /* GPIO3 and CM7_GPIO3 share same IO MUX function, GPIO_MUX3 selects one GPIO function: 0x8000U */
	    );

	  IOMUXC_SetPinConfig(
	      IOMUXC_GPIO_SD_B1_00_USDHC1_CMD,        /* GPIO_SD_B1_00 PAD functional properties : */
	      0x04U);                                 /* PDRV Field: high drive strength
	                                                 Pull Down Pull Up Field: Internal pullup resistor enabled
	                                                 Open Drain Field: Disabled
	                                                 Domain write protection: Both cores are allowed
	                                                 Domain write protection lock: Neither of DWP bits is locked */
	  IOMUXC_SetPinConfig(
	      IOMUXC_GPIO_SD_B1_01_USDHC1_CLK,        /* GPIO_SD_B1_01 PAD functional properties : */
	      0x0CU);                                 /* PDRV Field: high drive strength
	                                                 Pull Down Pull Up Field: No Pull
	                                                 Open Drain Field: Disabled
	                                                 Domain write protection: Both cores are allowed
	                                                 Domain write protection lock: Neither of DWP bits is locked */
	  IOMUXC_SetPinConfig(
	      IOMUXC_GPIO_SD_B1_02_USDHC1_DATA0,      /* GPIO_SD_B1_02 PAD functional properties : */
	      0x04U);                                 /* PDRV Field: high drive strength
	                                                 Pull Down Pull Up Field: Internal pullup resistor enabled
	                                                 Open Drain Field: Disabled
	                                                 Domain write protection: Both cores are allowed
	                                                 Domain write protection lock: Neither of DWP bits is locked */
	  IOMUXC_SetPinConfig(
	      IOMUXC_GPIO_SD_B1_03_USDHC1_DATA1,      /* GPIO_SD_B1_03 PAD functional properties : */
	      0x04U);                                 /* PDRV Field: high drive strength
	                                                 Pull Down Pull Up Field: Internal pullup resistor enabled
	                                                 Open Drain Field: Disabled
	                                                 Domain write protection: Both cores are allowed
	                                                 Domain write protection lock: Neither of DWP bits is locked */
	  IOMUXC_SetPinConfig(
	      IOMUXC_GPIO_SD_B1_04_USDHC1_DATA2,      /* GPIO_SD_B1_04 PAD functional properties : */
	      0x04U);                                 /* PDRV Field: high drive strength
	                                                 Pull Down Pull Up Field: Internal pullup resistor enabled
	                                                 Open Drain Field: Disabled
	                                                 Domain write protection: Both cores are allowed
	                                                 Domain write protection lock: Neither of DWP bits is locked */
	  IOMUXC_SetPinConfig(
	      IOMUXC_GPIO_SD_B1_05_USDHC1_DATA3,      /* GPIO_SD_B1_05 PAD functional properties : */
	      0x04U);                                 /* PDRV Field: high drive strength
	                                                 Pull Down Pull Up Field: Internal pullup resistor enabled
	                                                 Open Drain Field: Disabled
	                                                 Domain write protection: Both cores are allowed
	                                                 Domain write protection lock: Neither of DWP bits is locked */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitXipFlexSPI1Pins:
- options: {callFromInitBoot: 'true', coreID: cm7, enableClock: 'true'}
- pin_list:
  - {pin_num: F15, peripheral: FLEXSPI1, signal: FLEXSPI_A_DATA0, pin_signal: GPIO_SD_B2_08}
  - {pin_num: H15, peripheral: FLEXSPI1, signal: FLEXSPI_A_DATA1, pin_signal: GPIO_SD_B2_09}
  - {pin_num: H14, peripheral: FLEXSPI1, signal: FLEXSPI_A_DATA2, pin_signal: GPIO_SD_B2_10}
  - {pin_num: F16, peripheral: FLEXSPI1, signal: FLEXSPI_A_DATA3, pin_signal: GPIO_SD_B2_11}
  - {pin_num: E14, peripheral: FLEXSPI1, signal: FLEXSPI_A_DQS, pin_signal: GPIO_SD_B2_05, pull_down_pull_up_config: No_Pull}
  - {pin_num: G14, peripheral: FLEXSPI1, signal: FLEXSPI_A_SCLK, pin_signal: GPIO_SD_B2_07}
  - {pin_num: E15, peripheral: FLEXSPI1, signal: FLEXSPI_B_DATA0, pin_signal: GPIO_SD_B2_03}
  - {pin_num: H13, peripheral: FLEXSPI1, signal: FLEXSPI_B_DATA1, pin_signal: GPIO_SD_B2_02}
  - {pin_num: J14, peripheral: FLEXSPI1, signal: FLEXSPI_B_DATA2, pin_signal: GPIO_SD_B2_01}
  - {pin_num: J15, peripheral: FLEXSPI1, signal: FLEXSPI_B_DATA3, pin_signal: GPIO_SD_B2_00}
  - {pin_num: F14, peripheral: FLEXSPI1, signal: FLEXSPI_A_SS1_B, pin_signal: GPIO_SD_B2_04}
  - {pin_num: F17, peripheral: FLEXSPI1, signal: FLEXSPI_A_SS0_B, pin_signal: GPIO_SD_B2_06}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitXipFlexSPI1Pins, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitXipFlexSPI1Pins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* LPCG on: LPCG is ON. */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B2_00_FLEXSPI1_B_DATA03,  /* GPIO_SD_B2_00 is configured as FLEXSPI1_B_DATA03 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B2_01_FLEXSPI1_B_DATA02,  /* GPIO_SD_B2_01 is configured as FLEXSPI1_B_DATA02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B2_02_FLEXSPI1_B_DATA01,  /* GPIO_SD_B2_02 is configured as FLEXSPI1_B_DATA01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B2_03_FLEXSPI1_B_DATA00,  /* GPIO_SD_B2_03 is configured as FLEXSPI1_B_DATA00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B2_04_FLEXSPI1_A_SS1_B,  /* GPIO_SD_B2_04 is configured as FLEXSPI1_A_SS1_B */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B2_05_FLEXSPI1_A_DQS,    /* GPIO_SD_B2_05 is configured as FLEXSPI1_A_DQS */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B2_06_FLEXSPI1_A_SS0_B,  /* GPIO_SD_B2_06 is configured as FLEXSPI1_A_SS0_B */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B2_07_FLEXSPI1_A_SCLK,   /* GPIO_SD_B2_07 is configured as FLEXSPI1_A_SCLK */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B2_08_FLEXSPI1_A_DATA00,  /* GPIO_SD_B2_08 is configured as FLEXSPI1_A_DATA00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B2_09_FLEXSPI1_A_DATA01,  /* GPIO_SD_B2_09 is configured as FLEXSPI1_A_DATA01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B2_10_FLEXSPI1_A_DATA02,  /* GPIO_SD_B2_10 is configured as FLEXSPI1_A_DATA02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B2_11_FLEXSPI1_A_DATA03,  /* GPIO_SD_B2_11 is configured as FLEXSPI1_A_DATA03 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_SD_B2_05_FLEXSPI1_A_DQS,    /* GPIO_SD_B2_05 PAD functional properties : */
      0x0CU);                                 /* PDRV Field: high drive strength
                                                 Pull Down Pull Up Field: No Pull
                                                 Open Drain Field: Disabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitDebugUartsPins:
- options: {callFromInitBoot: 'true', coreID: cm7, enableClock: 'true'}
- pin_list:
  - {pin_num: K1, peripheral: LPUART6, signal: TXD, pin_signal: GPIO_EMC_B1_40}
  - {pin_num: L1, peripheral: LPUART6, signal: RXD, pin_signal: GPIO_EMC_B1_41}
  - {pin_num: B5, peripheral: LPUART8, signal: TXD, pin_signal: GPIO_DISP_B2_08}
  - {pin_num: D8, peripheral: LPUART8, signal: RXD, pin_signal: GPIO_DISP_B2_09}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitDebugUartsPins, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitDebugUartsPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* LPCG on: LPCG is ON. */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B2_08_LPUART8_TXD,     /* GPIO_DISP_B2_08 is configured as LPUART8_TXD */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B2_09_LPUART8_RXD,     /* GPIO_DISP_B2_09 is configured as LPUART8_RXD */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_40_LPUART6_TXD,      /* GPIO_EMC_B1_40 is configured as LPUART6_TXD */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_41_LPUART6_RXD,      /* GPIO_EMC_B1_41 is configured as LPUART6_RXD */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitUserButtonsPins:
- options: {callFromInitBoot: 'true', coreID: cm7, enableClock: 'true'}
- pin_list:
  - {pin_num: P8, peripheral: GPIO6, signal: 'gpio_mux_io, 06', pin_signal: GPIO_LPSR_06, direction: INPUT, gpio_interrupt: kGPIO_IntRisingEdge, pull_up_down_config: Pull_Up,
    pull_keeper_select: Pull, drive_strength: Normal}
  - {pin_num: R8, peripheral: GPIO6, signal: 'gpio_mux_io, 07', pin_signal: GPIO_LPSR_07, direction: INPUT, gpio_interrupt: kGPIO_IntRisingEdge, pull_up_down_config: Pull_Up,
    pull_keeper_select: Pull, drive_strength: Normal}
  - {pin_num: U8, peripheral: GPIO6, signal: 'gpio_mux_io, 08', pin_signal: GPIO_LPSR_08, direction: INPUT, gpio_interrupt: kGPIO_IntRisingEdge, pull_up_down_config: Pull_Up,
    pull_keeper_select: Pull, drive_strength: Normal}
  - {pin_num: P5, peripheral: GPIO6, signal: 'gpio_mux_io, 09', pin_signal: GPIO_LPSR_09, direction: INPUT, gpio_interrupt: kGPIO_IntRisingEdge, pull_up_down_config: Pull_Up,
    pull_keeper_select: Pull, drive_strength: Normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitUserButtonsPins, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitUserButtonsPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc_Lpsr);      /* LPCG on: LPCG is ON. */

  /* GPIO configuration of USER_BUTTON1 on IOMUXC_LPSR_SW_MUX_CTL_PAD_GPIO_LPSR_06 (pin P8) */
  gpio_pin_config_t USER_BUTTON1_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_IntRisingEdge
  };
  /* Initialize GPIO functionality on IOMUXC_LPSR_SW_MUX_CTL_PAD_GPIO_LPSR_06 (pin P8) */
  GPIO_PinInit(GPIO6, 6U, &USER_BUTTON1_config);
  /* Enable GPIO pin interrupt on IOMUXC_LPSR_SW_MUX_CTL_PAD_GPIO_LPSR_06 (pin P8) */

  /* GPIO configuration of USER_BUTTON2 on IOMUXC_LPSR_SW_MUX_CTL_PAD_GPIO_LPSR_07 (pin R8) */
  gpio_pin_config_t USER_BUTTON2_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_IntRisingEdge
  };
  /* Initialize GPIO functionality on IOMUXC_LPSR_SW_MUX_CTL_PAD_GPIO_LPSR_07 (pin R8) */
  GPIO_PinInit(GPIO6, 7U, &USER_BUTTON2_config);
  /* Enable GPIO pin interrupt on IOMUXC_LPSR_SW_MUX_CTL_PAD_GPIO_LPSR_07 (pin R8) */

  /* GPIO configuration of USER_BUTTON3 on IOMUXC_LPSR_SW_MUX_CTL_PAD_GPIO_LPSR_08 (pin U8) */
  gpio_pin_config_t USER_BUTTON3_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_IntRisingEdge
  };
  /* Initialize GPIO functionality on IOMUXC_LPSR_SW_MUX_CTL_PAD_GPIO_LPSR_08 (pin U8) */
  GPIO_PinInit(GPIO6, 8U, &USER_BUTTON3_config);
  /* Enable GPIO pin interrupt on IOMUXC_LPSR_SW_MUX_CTL_PAD_GPIO_LPSR_08 (pin U8) */

  /* GPIO configuration of USER_BUTTON4 on IOMUXC_LPSR_SW_MUX_CTL_PAD_GPIO_LPSR_09 (pin P5) */
  gpio_pin_config_t USER_BUTTON4_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_IntRisingEdge
  };
  /* Initialize GPIO functionality on IOMUXC_LPSR_SW_MUX_CTL_PAD_GPIO_LPSR_09 (pin P5) */
  GPIO_PinInit(GPIO6, 9U, &USER_BUTTON4_config);
  /* Enable GPIO pin interrupt on IOMUXC_LPSR_SW_MUX_CTL_PAD_GPIO_LPSR_09 (pin P5) */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_LPSR_06_GPIO_MUX6_IO06,     /* GPIO_LPSR_06 is configured as GPIO_MUX6_IO06 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_LPSR_07_GPIO_MUX6_IO07,     /* GPIO_LPSR_07 is configured as GPIO_MUX6_IO07 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_LPSR_08_GPIO_MUX6_IO08,     /* GPIO_LPSR_08 is configured as GPIO_MUX6_IO08 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_LPSR_09_GPIO_MUX6_IO09,     /* GPIO_LPSR_09 is configured as GPIO_MUX6_IO09 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_LPSR_06_GPIO_MUX6_IO06,     /* GPIO_LPSR_06 PAD functional properties : */
      0x0CU);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: normal driver
                                                 Pull / Keep Select Field: Pull Enable
                                                 Pull Up / Down Config. Field: Weak pull up
                                                 Open Drain LPSR Field: Disabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_LPSR_07_GPIO_MUX6_IO07,     /* GPIO_LPSR_07 PAD functional properties : */
      0x0CU);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: normal driver
                                                 Pull / Keep Select Field: Pull Enable
                                                 Pull Up / Down Config. Field: Weak pull up
                                                 Open Drain LPSR Field: Disabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_LPSR_08_GPIO_MUX6_IO08,     /* GPIO_LPSR_08 PAD functional properties : */
      0x0CU);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: normal driver
                                                 Pull / Keep Select Field: Pull Enable
                                                 Pull Up / Down Config. Field: Weak pull up
                                                 Open Drain LPSR Field: Disabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_LPSR_09_GPIO_MUX6_IO09,     /* GPIO_LPSR_09 PAD functional properties : */
      0x0CU);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: normal driver
                                                 Pull / Keep Select Field: Pull Enable
                                                 Pull Up / Down Config. Field: Weak pull up
                                                 Open Drain LPSR Field: Disabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitUserLedsPins:
- options: {callFromInitBoot: 'true', coreID: cm7, enableClock: 'true'}
- pin_list:
  - {pin_num: C7, peripheral: GPIO5, signal: 'gpio_mux_io, 05', pin_signal: GPIO_DISP_B2_04}
  - {pin_num: C9, peripheral: GPIO5, signal: 'gpio_mux_io, 06', pin_signal: GPIO_DISP_B2_05}
  - {pin_num: C6, peripheral: GPIO5, signal: 'gpio_mux_io, 07', pin_signal: GPIO_DISP_B2_06}
  - {pin_num: D6, peripheral: GPIO5, signal: 'gpio_mux_io, 08', pin_signal: GPIO_DISP_B2_07}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitUserLedsPins, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitUserLedsPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* LPCG on: LPCG is ON. */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B2_04_GPIO_MUX5_IO05,  /* GPIO_DISP_B2_04 is configured as GPIO_MUX5_IO05 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B2_05_GPIO_MUX5_IO06,  /* GPIO_DISP_B2_05 is configured as GPIO_MUX5_IO06 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B2_06_GPIO_MUX5_IO07,  /* GPIO_DISP_B2_06 is configured as GPIO_MUX5_IO07 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B2_07_GPIO_MUX5_IO08,  /* GPIO_DISP_B2_07 is configured as GPIO_MUX5_IO08 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitSecureI2cPins:
- options: {callFromInitBoot: 'true', coreID: cm7, enableClock: 'true'}
- pin_list:
  - {pin_num: N7, peripheral: LPI2C5, signal: SDA, pin_signal: GPIO_LPSR_04}
  - {pin_num: N8, peripheral: LPI2C5, signal: SCL, pin_signal: GPIO_LPSR_05}
  - {pin_num: T7, peripheral: GPIO12, signal: 'gpio_io, 03', pin_signal: GPIO_LPSR_03, direction: OUTPUT, pull_up_down_config: Pull_Up, pull_keeper_select: Pull}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitSecureI2cPins, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitSecureI2cPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc_Lpsr);      /* LPCG on: LPCG is ON. */
  CLOCK_EnableClock(kCLOCK_Iomuxc);      /* LPCG on: LPCG is ON. */
  CLOCK_EnableClock(kCLOCK_Gpio);      /* LPCG on: LPCG is ON. */
  CLOCK_EnableClock(kCLOCK_Iomuxc);      /* LPCG on: LPCG is ON. */

  /* GPIO configuration of SECURITY_RST_BOOT_MODE1 on IOMUXC_LPSR_SW_MUX_CTL_PAD_GPIO_LPSR_03 (pin T7) */
  gpio_pin_config_t SECURITY_RST_BOOT_MODE1_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on IOMUXC_LPSR_SW_MUX_CTL_PAD_GPIO_LPSR_03 (pin T7) */
  GPIO_PinInit(GPIO6, 3U, &SECURITY_RST_BOOT_MODE1_config);

  IOMUXC_SetPinMux(
	 IOMUXC_GPIO_LPSR_03_GPIO_MUX6_IO03,        /* GPIO_LPSR_03 is configured as GPIO12_IO03 */
     0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
	  IOMUXC_GPIO_DISP_B2_11_LPI2C3_SDA,         /* GPIO_LPSR_04 is configured as LPI2C5_SDA */
      1U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
	  IOMUXC_GPIO_DISP_B2_10_LPI2C3_SCL,         /* GPIO_LPSR_05 is configured as LPI2C5_SCL */
      1U);
  /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinConfig(
	  IOMUXC_GPIO_DISP_B2_10_LPI2C3_SCL,           /* GPIO_AD_08 PAD functional properties : */
      0x10U);

  /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinConfig(
	  IOMUXC_GPIO_DISP_B2_11_LPI2C3_SDA,           /* GPIO_AD_08 PAD functional properties : */
      0x10U);

  IOMUXC_SetPinConfig(
	  IOMUXC_GPIO_LPSR_03_GPIO_MUX6_IO03,        /* GPIO_LPSR_03 PAD functional properties : */
      0x0EU);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: high driver
                                                 Pull / Keep Select Field: Pull Enable
                                                 Pull Up / Down Config. Field: Weak pull up
                                                 Open Drain LPSR Field: Disabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
}


/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
