#
# Copyright 2022 NXP 
#
# NXP Confidential and Proprietary. This software is owned or controlled by NXP and may only be used strictly
 * in accordance with the applicable license terms. By expressly accepting such terms or by downloading,
 * installing, activating and/or otherwise using the software, you are agreeing that you have read,
 * and that you agree to comply with and are bound by, such license terms. If you do not agree to be bound by
 * the applicable license terms, then you may not retain, install, activate or otherwise use the software.
#

# Other Targets

# if make is called with 'clean' as the first argument, prepare some special workaround to limit command line length 
ifeq (clean,$(firstword $(MAKECMDGOALS)))

# do not run any target exept for ones with + commands, this will skip 'clean', and assume it's done
MAKEFLAGS+=  -t

# get the files that exist and really need to be removed
cleanfiles := $(strip $(foreach f, $(EXECUTABLES) $(OBJS) $(C_DEPS) *.axf ,$(wildcard $(f))))

# create a .clean target name for them
cleantargets:=$(patsubst %,%.clean,$(cleanfiles))

# they do not exist as files 
.PHONY: $(cleantargets)

# add targets as an order dependency to 'clean' to get them executed with 'clean'
clean: | $(cleantargets) $(info make: Using 'clean' workaround from 'makefile.targets'. )

# # add a %.clean pattern rule for each file, with a + to force execution 
$(cleantargets): %.clean : %
	+@${RM} $<

# end of section only for 'clean' target
endif
