/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _VERIFY_CONFIG_H_
#define _VERIFY_CONFIG_H_

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */
#include <qmc2_types.h>

/***********************************************************************************************************************
 * Verify_Rdc_Config
 **********************************************************************************************************************/
 sss_status_t Verify_Rdc_Config(uint8_t *cmpSha512);


#if defined(__cplusplus)
}
#endif

#endif /* _VERIFY_CONFIG_H_ */
